version: '3.3'

services:
  api:
    build: ./api
    volumes:
  judge_server:
    build: ./judge_server
      - ./api/:/app
        #    command: python manage.py runserver 0.0.0.0:8000
    ports:
  db:
      - 8000:8000
    links:
      - postgres
 
    build: ./postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      #      POSTGRES_USER: "daizu"
      POSTGRES_PASSWORD: "daizuhogehoge" 
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    #    user: "dauzu"

  mq:
    build: ./rabbitmq
    restart: always
