version: '3.3'

services:
  application:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./:/app

  judge_server:
    build: ./judge_server
    ports:
      - "8000:8000"

  postgres:
    build: ./postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      #      POSTGRES_USER: "daizu"
      POSTGRES_PASSWORD: "daizuhogehoge" 
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    #    user: "dauzu"

  mq:
    build: ./rabbitmq
    restart: always

