# Generated by Django 2.2.1 on 2019-05-06 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_schedule', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('contest_tag', models.CharField(max_length=15)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField()),
                ('writer', models.CharField(max_length=30)),
                ('top_page', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_tag', models.CharField(max_length=15)),
                ('problem_name', models.CharField(max_length=20)),
                ('problem_tag', models.CharField(max_length=15)),
                ('problem_order', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField(default=256)),
                ('problem', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('example_input_output', models.TextField()),
                ('answer', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistContestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_tag', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Submittion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_tag', models.CharField(max_length=15)),
                ('problem_tag', models.CharField(max_length=15)),
                ('source_code', models.TextField()),
                ('author', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('status', models.CharField(blank=True, max_length=5)),
                ('warning', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('time', models.FloatField(blank=True)),
                ('memory', models.IntegerField(blank=True)),
                ('byte', models.IntegerField(blank=True)),
                ('date', models.DateTimeField(blank=True)),
                ('is_judge', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
